name: Check PR category and type
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]
jobs:
  check_label:
    runs-on: ubuntu-latest
    name: Check PR Category and Type
    env:
      NEW_FEATURE_COUNT: 0
      ENHANCEMENT_COUNT: 0
    steps:
      - if: contains(github.event.pull_request.labels.*.name, 'New Feature')
        id: new-feature
        run: echo "NEW_FEATURE_COUNT=1" >> $GITHUB_ENV
      - if: contains(github.event.pull_request.labels.*.name, 'Enhancement')
        id: enhancement
        run: echo "ENHANCEMENT_COUNT=1" >> $GITHUB_ENV
      # - if: contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
      #   id: bug-fix
      #   run: echo '::set-env name=COUNT::1'
      # - if: contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
      #   id: not-yet-enabled
      #   run: echo '::set-env name=COUNT::1'
      # - if: contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      #   id: skip-release-notes
      #   run: echo '::set-env name=COUNT::1'

      - run: |
          # ONE=${{env.NEW_FEATURE_COUNT}}
          # TWO=${{env.ENHANCEMENT_COUNT}}
          LABELS_COUNT=$((${{env.NEW_FEATURE_COUNT}}+${{env.ENHANCEMENT_COUNT}}))
          echo $LABELS_COUNT
      - run: echo $LABELS_COUNT

      # - name: "Failed to find proper PR Type label. Please add one of the following: 'New Feature', 'Enhancement', or 'Bug-Fix'"
      #   run: exit 1
      #   if: |
      #     !contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      #     !contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
      #     !contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
      #     !contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled') &&
      #     !contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      # - name: "Found more than one PR Type label. Please add only one of the following: 'New Feature', 'Enhancement', 'Bug-Fix', 'Not-Yet-Enabled', or 'Skip-Release-Notes'"
      #   run: exit 1
      #   if: |
      #     (
      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      #       contains(github.event.pull_request.labels.*.name, 'Enhancement')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'New Feature') &&
      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Enhancement') &&
      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Bug-Fix') &&
      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      #     ) || (
      #       contains(github.event.pull_request.labels.*.name, 'Not-Yet-Enabled') &&
      #       contains(github.event.pull_request.labels.*.name, 'Skip-Release-Notes')
      #     )
      # - name: "PR Category is missing from PR title. Please add it like '<category>: <pr title>'"
      #   run: |
      #     if [[ ! "${{ github.event.pull_request.title }}" =~ ^.{2,}\:.{2,} ]]; then
      #       exit 1
      #     fi
      # - name: "Found at least one PR Type label and Category in the title. Good job!"
      #   run: exit 0
